### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [watzon/tourmaline#6]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date
* Has the latest commit dated more than a year ago

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by watzon** [comment]
I haven't had the time to maintain it lately, but as soon as I'm able I'll make it work with 0.26.1

**Comment by watzon** [comment]
I am finally back from a long coding break and have quite the backlog. I'll be fixing this as soon as I'm able. PRs are always welcome as well.

**Comment by watzon** [comment]
@vladfaust this is officially working with Crystal 0.28.0 and I am currently maintaining it again. Do I need to submit a PR to get it re-added to Awesome Crystal?

**Comment by vladfaust** [comment]
@watzon thanks for your effort, I'm glad we've got the Telegram Bot API shard working again! You have to open a PR yourself.
